// <auto-generated />
namespace ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class UPDUserInCustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UPDUserInCustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201805152030156_UPDUserInCustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
